<?xml version="1.0" standalone="yes"?><!DOCTYPE configrecord [  <!ELEMENT configrecord (configgroup+)><!ELEMENT configgroup (configitem+)><!ELEMENT configitem (value+)><!ELEMENT value (#PCDATA)><!ATTLIST configrecord version CDATA #IMPLIED><!ATTLIST configgroup name CDATA #IMPLIED><!ATTLIST configgroup instance CDATA #IMPLIED><!ATTLIST configitem name CDATA #IMPLIED><!ATTLIST configitem instance CDATA #IMPLIED><!ATTLIST value name CDATA #IMPLIED>]>
<configrecord version="0.1.0.1">
    <configgroup name="Interface" instance="wlan0">
        <configitem name="State">
            <value>Enabled</value>
        </configitem>
        <configitem name="DHCP Client">
            <value>Disabled</value>
        </configitem>
        <configitem name="IP Address">
            <value>192.168.111.111</value>
        </configitem>
        <configitem name="Default Gateway">
            <value>255.255.252.0</value>
        </configitem>
    </configgroup>
</configrecord>