<?xml version="1.0" standalone="yes"?>
<!-- Automatically generated XML -->
<!DOCTYPE statusrecord [
   <!ELEMENT statusrecord (statusgroup+)>
   <!ELEMENT statusgroup (statusitem+,statusgroup*)>
   <!ELEMENT statusitem (value+)>
   <!ELEMENT value (#PCDATA)>
   <!ATTLIST statusrecord version CDATA #IMPLIED>
   <!ATTLIST statusgroup name CDATA #IMPLIED>
   <!ATTLIST statusgroup instance CDATA #IMPLIED>
   <!ATTLIST statusitem name CDATA #IMPLIED>
   <!ATTLIST statusitem instance CDATA #IMPLIED>
   <!ATTLIST value name CDATA #IMPLIED>
]>
<statusrecord version = "0.1.0.1">
   <statusgroup name = "Access Point" instance = "ap0">
      <statusitem name = "State">
         <value>Up</value>
      </statusitem>
      <statusitem name = "BSSID">
         <value>02:80:a3:ee:fd:00</value>
      </statusitem>
      <statusitem name = "SSID">
         <value>standard001</value>
      </statusitem>
      <statusitem name = "Encryption">
         <value>CCMP</value>
      </statusitem>
      <statusitem name = "Security Suite">
         <value>WPA2</value>
      </statusitem>
      <statusitem name = "Band">
         <value>5 GHz</value>
      </statusitem>
      <statusitem name = "Channel">
         <value>64</value>
      </statusitem>
      <statusitem name = "Clients">
         <value>0</value>
      </statusitem>
   </statusgroup>
   <statusgroup name = "Clock">
      <statusitem name = "Current Time">
         <value>2007-01-01 14:17:32</value>
      </statusitem>
   </statusgroup>
   <statusgroup name = "CPM CPs">
      <statusitem name = "CP" instance = "1">
         <value name = "Ref">pin 38 / 50</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">0</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "2">
         <value name = "Ref">pin 12 / 48</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">0</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "3">
         <value name = "Ref">pin 8 / 46</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">1</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "4">
         <value name = "Ref">pin 9 / 44</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">1</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "5">
         <value name = "Ref">pin 15 / 58</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">0</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "6">
         <value name = "Ref">pin 16 / 60</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">0</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "7">
         <value name = "Ref">pin 10 / 42</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">1</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "8">
         <value name = "Ref">pin 11 / 40</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">1</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "9">
         <value name = "Ref">pin 22 / 16</value>
         <value name = "Usage">Output</value>
         <value name = "Assert">Low</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">1</value>
         <value name = "Roles">1</value>
         <value name = "Active in Role">WLAN Active</value>
      </statusitem>
      <statusitem name = "CP" instance = "10">
         <value name = "Ref">pin 37 / 62</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">0</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "11">
         <value name = "Ref">pin 40 / 68</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">0</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
      <statusitem name = "CP" instance = "12">
         <value name = "Ref">pin 39 / 66</value>
         <value name = "Usage">Unused</value>
         <value name = "Assert">High</value>
         <value name = "Mode">Push-Pull</value>
         <value name = "Value">-</value>
         <value name = "Roles">0</value>
         <value name = "Active in Role">&lt;available&gt;</value>
      </statusitem>
   </statusgroup>
   <statusgroup name = "CPM Roles">
      <statusitem name = "Role" instance = "AP Trigger">
         <value name = "Usage">Input</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "State">Inactive</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
      <statusitem name = "Role" instance = "Ethernet Link">
         <value name = "Usage">Output</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "State">Active</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
      <statusitem name = "Role" instance = "GSPI Slave Interrupt">
         <value name = "Usage">Output</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "State">Inactive</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
      <statusitem name = "Role" instance = "HTTP Server Trigger">
         <value name = "Usage">Input</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "State">Inactive</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
      <statusitem name = "Role" instance = "Keep AWAKE">
         <value name = "Usage">Input</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "State">Inactive</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
      <statusitem name = "Role" instance = "Line 1 DSR">
         <value name = "Usage">Input</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "State">Inactive</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
      <statusitem name = "Role" instance = "Line 1 DTR">
         <value name = "Usage">Output</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "State">Active</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
      <statusitem name = "Role" instance = "Radio Trigger">
         <value name = "Usage">Input</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "State">Inactive</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
      <statusitem name = "Role" instance = "SPI.CS">
         <value name = "Usage">Reserved</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "May Use CP">8</value>
      </statusitem>
      <statusitem name = "Role" instance = "SPI.MISO">
         <value name = "Usage">Reserved</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "May Use CP">3</value>
      </statusitem>
      <statusitem name = "Role" instance = "SPI.MOSI">
         <value name = "Usage">Reserved</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "May Use CP">4</value>
      </statusitem>
      <statusitem name = "Role" instance = "SPI.SCK">
         <value name = "Usage">Reserved</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "May Use CP">7</value>
      </statusitem>
      <statusitem name = "Role" instance = "User Data Updated">
         <value name = "Usage">Output</value>
         <value name = "Using CP">&lt;unused&gt;</value>
         <value name = "State">Inactive</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
      <statusitem name = "Role" instance = "WLAN Active">
         <value name = "Usage">Output</value>
         <value name = "Using CP">9</value>
         <value name = "State">Active</value>
         <value name = "May Use CP">&lt;any&gt;</value>
      </statusitem>
   </statusgroup>
   <statusgroup name = "Device">
      <statusitem name = "Product Type">
         <value>xPico240</value>
      </statusitem>
      <statusitem name = "Product ID">
         <value>Y2</value>
      </statusitem>
      <statusitem name = "Product SKU">
         <value>XPC240100</value>
      </statusitem>
      <statusitem name = "Antenna">
         <value>U.FL</value>
      </statusitem>
      <statusitem name = "Serial Number">
         <value>0080A3EEFCFF</value>
      </statusitem>
      <statusitem name = "Configuration Version">
         <value>[unversioned]</value>
      </statusitem>
      <statusitem name = "Configuration Modified">
         <value>Yes</value>
      </statusitem>
      <statusitem name = "Firmware Version">
         <value>4.8.0.0R6</value>
      </statusitem>
      <statusitem name = "Active Partition">
         <value>2</value>
      </statusitem>
      <statusitem name = "Build Date">
         <value>Jun 12 2021 (04:51:52)</value>
      </statusitem>
      <statusitem name = "Bootloader Version">
         <value>1.3.0.0R1</value>
      </statusitem>
      <statusitem name = "Bootloader Date">
         <value>Jun 28 2018 09:58:10</value>
      </statusitem>
      <statusitem name = "Uptime">
         <value>1 hour 28 minutes 58 seconds</value>
      </statusitem>
      <statusitem name = "Permanent Config">
         <value>Saved</value>
      </statusitem>
   </statusgroup>
   <statusgroup name = "Diagnostics Buffer Pools">
      <statusitem name = "Buffer Pool" instance = "Transmit">
         <value name = "Total">80</value>
         <value name = "Free">76</value>
      </statusitem>
      <statusitem name = "Buffer Pool" instance = "Receive">
         <value name = "Total">120</value>
         <value name = "Free">98</value>
      </statusitem>
   </statusgroup>
   <statusgroup name = "Diagnostics Hardware">
      <statusitem name = "CPU Type">
         <value>BCM4390X id 0x1f23ab83</value>
      </statusitem>
      <statusitem name = "CPU Speed">
         <value>320000000 Hz</value>
      </statusitem>
      <statusitem name = "Backplane Speed">
         <value>160000000 Hz</value>
      </statusitem>
      <statusitem name = "RAM Size">
         <value>2097152 Bytes</value>
      </statusitem>
      <statusitem name = "Flash Size">
         <value>8388608 Bytes</value>
      </statusitem>
   </statusgroup>
   <statusgroup name = "Diagnostics Heap">
      <statusitem name = "Total">
         <value>753608 bytes</value>
      </statusitem>
      <statusitem name = "Minimum Available">
         <value>544884 bytes</value>
      </statusitem>
      <statusitem name = "Available">
         <value>564420 bytes</value>
      </statusitem>
      <statusitem name = "Number of Fragments">
         <value>2</value>
      </statusitem>
      <statusitem name = "Largest Fragment Available">
         <value>564144 bytes</value>
      </statusitem>
      <statusitem name = "Allocated Blocks">
         <value>432</value>
      </statusitem>
      <statusitem name = "Number of Allocs Failed">
         <value>0</value>
      </statusitem>
      <statusitem name = "Status">
         <value>Okay</value>
      </statusitem>
   </statusgroup>
   <statusgroup name = "Diagnostics IP Sockets">
      <statusitem name = "IP Socket" instance = "1">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">eth0</value>
         <value name = "Local Port">23</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "2">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">lo0</value>
         <value name = "Local Port">23</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "3">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">eth0</value>
         <value name = "Local Port">8080</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "4">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">lo0</value>
         <value name = "Local Port">8080</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "5">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">eth0</value>
         <value name = "Local Port">443</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "6">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">lo0</value>
         <value name = "Local Port">443</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "7">
         <value name = "Protocol">UDP</value>
         <value name = "Interface">eth0</value>
         <value name = "Local Port">30718</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "8">
         <value name = "Protocol">UDP</value>
         <value name = "Interface">eth0</value>
         <value name = "Local Port">68</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">174</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "9">
         <value name = "Protocol">UDP</value>
         <value name = "Interface">ap0</value>
         <value name = "Local Port">67</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "10">
         <value name = "Protocol">UDP</value>
         <value name = "Interface">ap0</value>
         <value name = "Local Port">53</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "11">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">ap0</value>
         <value name = "Local Port">8080</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "12">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">ap0</value>
         <value name = "Local Port">443</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "13">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">ap0</value>
         <value name = "Local Port">23</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "14">
         <value name = "Protocol">UDP</value>
         <value name = "Interface">ap0</value>
         <value name = "Local Port">30718</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "15">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">wlan0</value>
         <value name = "Local Port">23</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "16">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">wlan0</value>
         <value name = "Local Port">8080</value>
         <value name = "Remote Address">10.10.71.181</value>
         <value name = "Remote Port">57548</value>
         <value name = "State">Established</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">2</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "17">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">wlan0</value>
         <value name = "Local Port">443</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "18">
         <value name = "Protocol">UDP</value>
         <value name = "Interface">wlan0</value>
         <value name = "Local Port">30718</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "19">
         <value name = "Protocol">TCP</value>
         <value name = "Interface">wlan0</value>
         <value name = "Local Port">8080</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Listen</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "20">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "21">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "22">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "23">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "24">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "25">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "26">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "27">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "28">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "29">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "30">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "31">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "32">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "33">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "34">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "35">
         <value name = "Protocol">None</value>
         <value name = "Interface"></value>
         <value name = "Local Port">0</value>
         <value name = "Remote Address"></value>
         <value name = "Remote Port">0</value>
         <value name = "State">Uninitialized</value>
         <value name = "Rx Buffers">0</value>
         <value name = "Tx Buffers">0</value>
      </statusitem>
      <statusitem name = "IP Socket" instance = "36">