<?xml version='1.0'  standalone='yes'?>
<!-- Automatically generated XML --> <!DOCTYPE configrecord [
        <!ELEMENT configrecord (configgroup+)>
        <!ELEMENT configgroup (configitem+)>
        <!ELEMENT configitem (value+)>
        <!ELEMENT value (#PCDATA)>
        <!ATTLIST configrecord version CDATA #IMPLIED>
        <!ATTLIST configgroup name CDATA #IMPLIED>
        <!ATTLIST configgroup instance CDATA #IMPLIED>
        <!ATTLIST configitem name CDATA #IMPLIED>
        <!ATTLIST configitem instance CDATA #IMPLIED>
        <!ATTLIST value name CDATA #IMPLIED>
        ]>
<configrecord version="0.1.0.1">
    <configgroup name="Access Point" instance="ap0">
        <configitem name="SSID">
            <value>23456789</value>
        </configitem>
        <configitem name="Passphrase">
            <value>standard</value>
        </configitem>
    </configgroup>
    <configgroup name="Interface" instance="ap0">
        <configitem name="State">
            <value>Enabled</value>
        </configitem>
        <configitem name="IP Address">
            <value>192.168.0.1/24</value>
        </configitem>
        <configitem name="Default Gateway">
            <value>&lt;None&gt;</value>
        </configitem>
        <configitem name="DHCP IP Address Range">
            <value name="Start">192.168.0.6</value>
            <value name="End">192.168.0.220</value>
        </configitem>
    </configgroup>
    <configgroup name="Interface" instance="wlan0">
            <configitem name="State">
                <value>Disabled</value>
            </configitem>
        </configgroup>
    <configgroup name="HTTP Server">
        <configitem name="Port">
            <value>8080</value>
        </configitem>
    </configgroup>
</configrecord>