<?xml version='1.0'  standalone='yes'?>
<!DOCTYPE configrecord [<!ELEMENT configrecord (configgroup+)>
                                    <!ELEMENT configgroup (configitem+)>
                                    <!ELEMENT configitem (value+)>
                                    <!ELEMENT value (#PCDATA)>
                                    <!ATTLIST configrecord version CDATA #IMPLIED>
                                    <!ATTLIST configgroup name CDATA #IMPLIED>
                                    <!ATTLIST configgroup instance CDATA #IMPLIED>
                                    <!ATTLIST configitem name CDATA #IMPLIED>
                                    <!ATTLIST configitem instance CDATA #IMPLIED>
                                    <!ATTLIST value name CDATA #IMPLIED>
                                    ]>
<configrecord version="0.1.0.1">
    <configgroup name="Bridge">
        <configitem name="Interface">
            <value>ap0</value>
        </configitem>
        <configitem name="Ethernet">
            <value name="State">enabled</value>
        </configitem>
    </configgroup>
</configrecord>