<?xml version="1.0" standalone="yes"?>
<!-- Automatically generated XML -->
<!DOCTYPE configrecord [
        <!ELEMENT configrecord (configgroup+)>
        <!ELEMENT configgroup (configitem+)>
        <!ELEMENT configitem (value+)>
        <!ELEMENT value (#PCDATA)>
        <!ATTLIST configrecord version CDATA #IMPLIED>
        <!ATTLIST configgroup name CDATA #IMPLIED>
        <!ATTLIST configgroup instance CDATA #IMPLIED>
        <!ATTLIST configitem name CDATA #IMPLIED>
        <!ATTLIST configitem instance CDATA #IMPLIED>
        <!ATTLIST value name CDATA #IMPLIED>
        ]>
<configrecord version="0.1.0.1">
    <configgroup name="Access Point" instance="ap0">
        <configitem name="SSID">
            <value>standard001</value>
        </configitem>
        <configitem name="Passphrase">
            <value>&lt;Configured&gt;</value>
        </configitem>
    </configgroup>
    <configgroup name="HTTP Server">
        <configitem name="Port">
            <value>8080</value>
        </configitem>
    </configgroup>
    <configgroup name="Interface" instance="ap0">
        <configitem name="State">
            <value>Disabled</value>
        </configitem>
        <configitem name="IP Address">
            <value>192.168.0.1/24</value>
        </configitem>
        <configitem name="Default Gateway">
            <value>&lt;None&gt;</value>
        </configitem>
        <configitem name="Primary DNS">
            <value>&lt;None&gt;</value>
        </configitem>
        <configitem name="Secondary DNS">
            <value>&lt;None&gt;</value>
        </configitem>
        <configitem name="DHCP IP Address Range">
            <value name="Start">192.168.0.6</value>
            <value name="End">192.168.0.220</value>
        </configitem>
    </configgroup>
    <configgroup name="Interface" instance="wlan0">
        <configitem name="State">
            <value>Enabled</value>
        </configitem>
        <configitem name="DHCP Client">
            <value>Disabled</value>
        </configitem>
        <configitem name="IP Address">
            <value>10.10.70.94/22</value>
        </configitem>
        <configitem name="Default Gateway">
            <value>10.10.70.1</value>
        </configitem>
        <configitem name="Primary DNS">
            <value>&lt;None&gt;</value>
        </configitem>
        <configitem name="Secondary DNS">
            <value>&lt;None&gt;</value>
        </configitem>
    </configgroup>
    <configgroup name = "Radio">
      <configitem name = "Band">
         <value>Dual</value>
      </configitem>
   </configgroup>
</configrecord>
