<?xml version='1.0'  standalone='yes'?>
<!DOCTYPE configrecord [<!ELEMENT configrecord (configgroup+)>
                                    <!ELEMENT configgroup (configitem+)>
                                    <!ELEMENT configitem (value+)>
                                    <!ELEMENT value (#PCDATA)>
                                    <!ATTLIST configrecord version CDATA #IMPLIED>
                                    <!ATTLIST configgroup name CDATA #IMPLIED>
                                    <!ATTLIST configgroup instance CDATA #IMPLIED>
                                    <!ATTLIST configitem name CDATA #IMPLIED>
                                    <!ATTLIST configitem instance CDATA #IMPLIED>
                                    <!ATTLIST value name CDATA #IMPLIED>
                                    ]>
<configrecord version="0.1.0.1">
    <configgroup name="WLAN Profile" instance="SR_office">
        <configitem name="Basic">
            <value name="Network Name">SR_office</value>
            <value name="State">Enabled</value>
        </configitem>
        <configitem name="Security">
            <value name="Suite">WPA2</value>
            <value name="WPAx Key Type">Passphrase</value>
            <value name="WPAx Passphrase">SR@office</value>
            <value name="WPAx Authentication">PSK</value>
            <value name="WPAx Encryption">CCMP</value>
        </configitem>
    </configgroup>
</configrecord>